services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - docker-network
    depends_on:
      - db
    command: sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app   # sync source code for hot reload
      - /app/node_modules # avoid overwriting node_modules
    ports:
      - "3000:3000"       # expose Vite dev server
    networks:
      - docker-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
    depends_on:
      - backend

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_DATABASE: [MYSQL_DATABASE]
      MYSQL_USER: [MYSQL_USER]
      MYSQL_PASSWORD: [MYSQL_PASSWORD]
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - docker-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - docker-network
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"

volumes:
  db-data:
  redis-data:
  frontend-build:

networks:
  docker-network:

    driver: bridge
